-- 테이블 삭제
DROP TABLE BOARD_T;

-- 테이블 생성
CREATE TABLE BOARD_T (
  BOARD_NO NUMBER NOT NULL,
  TITLE VARCHAR2(1000 BYTE) NOT NULL,
  CONTENT CLOB,
  MODIFIED_AT DATE,
  CREATED_AT DATE,
  CONSTRAINT PK_BOARD PRIMARY KEY (BOARD_NO)
);

-- 시퀀스 삭제
DROP SEQUENCE BOARD_SEQ;

-- 시퀀스 생성
CREATE SEQUENCE BOARD_SEQ NOCACHE;

INSERT INTO BOARD_T(BOARD_NO, TITLE, CONTENT,  MODIFIED_AT, CREATED_AT) VALUES (BOARD_SEQ.NEXTVAL, ?,?, SYSDATE, SYSDATE)
    
